### ISSUE TITLE
List EV spreads until Other is below 20%

### ISSUE THREAD

**Issue by n-rook** [Antar1011/Smogon-Usage-Stats#17]
Currently, the top 6 EV spreads are listed. This often means a large proportion of EV spreads aren't listed. For instance, view the 1695+ 2016-12 moveset stats:

http://www.smogon.com/stats/2016-12/moveset/ou-1695.txt

Over half of Landorus-Therian's used EV spreads are bucketed under Other.

I'd suggest that in addition to listing a minimum of 6 spreads, that spreads be listed until the Other bucket contains fewer than 20% of spreads.

I'd be happy to send a pull request to make this happen.

**Comment by Antar1011** [comment]
Not adding any new features to the legacy stats system, sorry. But I appreciate the feedback. I'll be incorporating something different for [Onix](https://github.com/Antar1011/Onix).

If you'd like to be involved in the discussion of what the new spread stats should look like, participate in this thread: http://www.smogon.com/forums/threads/the-future-of-spread-reports.3593442

Also note that all spreads are included in the JSON files located in the "chaos" folder of each month.

**Comment by n-rook** [comment]
Fair enough, that makes sense. Thanks for the pointer to the chaos directory, that does seem to have everything I'm interested in.
